modoboa/maillog/api/v2/urls.py
"""App related API urls."""

from rest_framework import routers

from . import viewsets

router = routers.SimpleRouter()
router.register(
    r"statistics", viewsets.StatisticsViewSet, basename="statistics")
router.register(
    r"logs/messages", viewsets.MaillogViewSet, basename="maillog")

urlpatterns = router.urls

modoboa/maillog/urls.py
"""Stats urls."""

from django.urls import path

from . import views

app_name = "maillog"

urlpatterns = [
    path("", views.index, name="fullindex"),
    path("graphs/", views.graphs, name="graph_list"),
    path("domains/", views.get_domain_list, name="domain_list"),
]

modoboa/maillog/models.py
"""App. related models."""

from django.db import models


class Maillog(models.Model):
    """A model to store message logs."""

    queue_id = models.CharField(max_length=50)
    date = models.DateTimeField(db_index=True)
    sender = models.EmailField()
    rcpt = models.EmailField()
    original_rcpt = models.EmailField(null=True)
    size = models.PositiveIntegerField()
    status = models.CharField(max_length=15)

    from_domain = models.ForeignKey(
        "admin.Domain", on_delete=models.SET_NULL, null=True,
        related_name="sent_messages_log"
    )
    to_domain = models.ForeignKey(
        "admin.Domain", on_delete=models.SET_NULL, null=True,
        related_name="recv_messages_log"
    )

    class Meta:
        ordering = ['date']

modoboa/maillog/forms.py
"""Modoboa stats forms."""

import rrdtool

from pkg_resources import parse_version

from django.conf import settings
from django.utils.translation import ugettext_lazy
from django import forms

from modoboa.lib import form_utils
from modoboa.parameters import forms as param_forms


class ParametersForm(param_forms.AdminParametersForm):
    """Stats global parameters."""

    app = "maillog"

    general_sep = form_utils.SeparatorField(label=ugettext_lazy("General"))

    logfile = forms.CharField(
        label=ugettext_lazy("Path to the log file"),
        initial="/var/log/mail.log",
        help_text=ugettext_lazy("Path to log file used to collect statistics"),
        widget=forms.TextInput(attrs={"class": "form-control"})
    )

    rrd_rootdir = forms.CharField(
        label=ugettext_lazy("Directory to store RRD files"),
        initial="/tmp/modoboa",
        help_text=ugettext_lazy(
            "Path to directory where RRD files are stored"),
        widget=forms.TextInput(attrs={"class": "form-control"})
    )

    greylist = form_utils.YesNoField(
        label=ugettext_lazy("Show greylisted messages"),
        initial=False,
        help_text=ugettext_lazy(
            "Differentiate between hard and soft rejects (greylisting)")
    )

    def __init__(self, *args, **kwargs):
        """Check RRDtool version."""
        super().__init__(*args, **kwargs)
        rrd_version = parse_version(rrdtool.lib_version())
        required_version = parse_version("1.6.0")
        test_mode = getattr(settings, "RRDTOOL_TEST_MODE", False)
        if rrd_version < required_version and not test_mode:
            del self.fields["greylist"]


def load_settings():
    """Load app settings."""
    from modoboa.parameters import tools as param_tools

    param_tools.registry.add(
        "global", ParametersForm, ugettext_lazy("Statistics"))

modoboa/maillog/views.py
# coding: utf-8

"""Custom views."""

import re
import time

from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import (
    login_required, user_passes_test, permission_required
)

from modoboa.admin.models import Domain
from modoboa.lib.exceptions import BadRequest, NotFound
from modoboa.lib.web_utils import (
    render_to_json_response
)

from . import signals
from .lib import date_to_timestamp


@login_required
@permission_required("admin.view_mailbox")
def index(request):
    """
    FIXME: how to select a default graph set ?
    """
    deflocation = "graphs/?gset=mailtraffic"
    if not request.user.is_superuser:
        if not Domain.objects.get_for_admin(request.user).count():
            raise NotFound(_("No statistics available"))

    graph_sets = {}
    for result in signals.get_graph_sets.send(
            sender="index", user=request.user):
        graph_sets.update(result[1])
    periods = [
        {"name": "day", "label": _("Day")},
        {"name": "week", "label": _("Week")},
        {"name": "month", "label": _("Month")},
        {"name": "year", "label": _("Year")},
        {"name": "custom", "label": _("Custom")}
    ]
    return render(request, 'maillog/index.html', {
        "periods": periods,
        "selection": "stats",
        "deflocation": deflocation,
        "graph_sets": graph_sets
    })


@login_required
@user_passes_test(lambda u: u.role != "SimpleUsers")
def graphs(request):
    gset = request.GET.get("gset", None)
    searchq = request.GET.get("searchquery", None)
    graph_sets = {}
    for result in signals.get_graph_sets.send(
            sender="index", user=request.user):
        graph_sets.update(result[1])
    if gset not in graph_sets:
        raise NotFound(_("Unknown graphic set"))
    period = request.GET.get("period", "day")
    tplvars = {"graphs": {}, "period": period}
    fname = graph_sets[gset].get_file_name(request.user, searchq)
    if fname is None:
        raise BadRequest(_("Unknown domain"))
    tplvars["fname"] = fname

    if period == "custom":
        if "start" not in request.GET or "end" not in request.GET:
            raise BadRequest(_("Bad custom period"))
        start = request.GET["start"]
        end = request.GET["end"]
        expr = re.compile(r'[:\- ]')
        period_name = "%s_%s" % (expr.sub('', start), expr.sub('', end))
        start = date_to_timestamp(expr.split(start))
        end = date_to_timestamp(expr.split(end))
    else:
        end = int(time.mktime(time.localtime()))
        start = "-1%s" % period
        period_name = period

    tplvars["domain_selector"] = graph_sets[gset].domain_selector
    tplvars["graphs"] = graph_sets[gset].export(tplvars["fname"], start, end)
    tplvars["period_name"] = period_name
    tplvars["start"] = start
    tplvars["end"] = end

    return render_to_json_response(tplvars)


@login_required
@user_passes_test(lambda u: u.role != "SimpleUsers")
def get_domain_list(request):
    """Get the list of domains the user can see."""
    doms = []
    for dom in Domain.objects.get_for_admin(request.user):
        doms += [dom.name]
        doms += [alias.name for alias in dom.domainalias_set.all()]

    return render_to_json_response(doms)

modoboa/maillog/templates/maillog/index.html
{% extends "twocols.html" %}
{% load i18n static %}

{% block pagetitle %}{% trans "Graphical statistics" %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'maillog/css/stats.css' %}" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/history.js' %}"></script>
<script type="text/javascript" src="{% static 'js/autocompleter.js' %}"></script>
<script type="text/javascript" src="{% static 'd3/d3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'maillog/js/d3.legend.js' %}"></script>
<script type="text/javascript" src="{% static 'maillog/js/graphic.js' %}"></script>
<script type="text/javascript" src="{% static 'maillog/js/stats.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    var stats = new Stats({
        graphurl: "{% url 'maillog:graph_list' %}",
        domain_list_url: "{% url 'maillog:domain_list' %}",
        deflocation: "{{ deflocation|safe }}",
        language: "{{ LANGUAGE_CODE }}"
    });
});
</script>
{% endblock %}

{% block leftcol %}
<ul class="nav nav-sidebar">
  {% for id, gset in graph_sets.items %}
    <li id="menu_{{ gset.html_id }}">
      <a href="#graphs?gset={{ gset.html_id }}">{{ gset.title }}</a>
    </li>
  {% endfor %}
</ul>
{% endblock %}

{% block apparea %}
<div id="menubar" class="row">
  <div id="domain-selector" class="col-sm-5">
    <form class="form-horizontal" role="form">
      <div class="form-group has-feedback">
        <input class="form-control" id="searchquery" type="text" value="{% trans 'Search a domain' %}">
        <span class="fa fa-search form-control-feedback"></span>
      </div>
    </form>
  </div>

  <div class="col-sm-7">
    <div class="btn-group" data-toggle="buttons">
      {% for p in periods %}
      <label class="btn btn-primary period_selector">
        <input type="radio" data-period="{{ p.name }}"> {% trans p.label %}
      </label>
      {% endfor %}
    </div>
  </div>
</div>

<div id="custom_period" class="row hidden">
  <div class="col-sm-7">
    <form class="form-inline">
      <span id="custom-period">
        <div class="form-group">
          <div class="input-group datetime_picker">
            <div class="input-group-addon"><span class="fa fa-outdent"></span></div>
            <input id="id_from" name="date_form" class="form-control" value="{{ start }}" type="text" readonly="readonly">
          </div>
        </div>
        <div class="form-group">
          <div class="input-group datetime_picker">
            <div class="input-group-addon"><span class="fa fa-outdent"></span></div>
            <input id="id_to" name="date_to" value="{{ end }}" class="form-control" type="text" readonly="readonly" />
          </div>
        </div>
        <button type="submit" class="btn btn-primary" id="customsend">{% trans "Apply" %}</button>
      </span>
    </form>
  </div>
</div>

<div id="graphs">
  {% for id, gset in graph_sets.items %}
  <div class="tab-pane {% if forloop.first %}active{% endif %}" id="graphs_{{ gset.html_id }}">
    <div id="gset"></div>
  </div>
  {% endfor %}
</div>

{% endblock %}