modoboa/core/templates/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'', include('modoboa.urls')),
)

modoboa/core/urls.py
"""Core urls."""

from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = "core"

urlpatterns = [
    path('', views.RootDispatchView.as_view(), name="root"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),

    path('accounts/login/', views.dologin, name="login"),
    path('accounts/logout/', views.dologout, name="logout"),
    path('accounts/2fa_verify/',
         views.TwoFactorCodeVerifyView.as_view(),
         name='2fa_verify'),

    path('core/', views.viewsettings, name="index"),
    path('core/parameters/', views.parameters, name="parameters"),
    path('core/info/', views.information, name="information"),
    path('core/logs/', views.logs, name="log_list"),
    path('core/logs/page/', views.logs_page, name="logs_page"),
    path('core/top_notifications/check/',
         views.check_top_notifications,
         name="top_notifications_check"),

    path('user/', views.index, name="user_index"),
    path('user/preferences/', views.preferences,
         name="user_preferences"),
    path('user/profile/', views.profile, name="user_profile"),
    path('user/api/', views.api_access, name="user_api_access"),
    path('user/security/', views.security, name="user_security"),
    path('robots.txt', TemplateView.as_view(template_name="core/robots.txt", content_type="text/plain")),
]

modoboa/urls.py
from functools import reduce

from ckeditor_uploader import views as cku_views

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from drf_spectacular.views import (
    SpectacularJSONAPIView, SpectacularSwaggerView, SpectacularRedocView
)

from modoboa.admin.views import user as user_views
from modoboa.core import signals as core_signals, views as core_views
from modoboa.core.extensions import exts_pool

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name="javascript-catalog"),

    path('ckeditor/upload/', login_required(cku_views.upload),
         name="ckeditor_upload"),
    path('ckeditor/browse/', login_required(cku_views.browse),
         name="ckeditor_browse"),

    path('', include("modoboa.core.urls")),
    path('admin/', include("modoboa.admin.urls")),
    path('dnstools/', include("modoboa.dnstools.urls")),
    path('pdfcredentials', include("modoboa.pdfcredentials.urls")),
    path('stats/', include("modoboa.maillog.urls")),
    path('dmarc/', include("modoboa.dmarc.urls")),

    path('user/forward/', user_views.forward, name="user_forward"),

    path('accounts/password_reset/', core_views.PasswordResetView.as_view(),
         name="password_reset"),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path('reset/confirm_code/',
         core_views.VerifySMSCodeView.as_view(),
         name="password_reset_confirm_code"),
    path('reset/resend_code/',
         core_views.ResendSMSCodeView.as_view(),
         name="password_reset_resend_code"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
]

exts_pool.load_all()
urlpatterns += exts_pool.get_urls()

extra_routes = core_signals.extra_uprefs_routes.send(sender="urls")
if extra_routes:
    extra_routes = reduce(
        lambda a, b: a + b, [route[1] for route in extra_routes])
    urlpatterns += extra_routes

# API urls
urlpatterns += [
    # FIXME: legacy, to remove ASAP
    path('docs/openapi.json',
         SpectacularJSONAPIView.as_view(api_version="v1"), name='schema-v1-legacy'),

    path('api/schema-v1/',
         SpectacularJSONAPIView.as_view(api_version="v1"), name='schema-v1'),
    path('api/schema-v1/swagger/',
         SpectacularSwaggerView.as_view(url_name='schema-v1'),
         name='docs-index-v1'),
    path('api/schema-v1/redoc/',
         SpectacularRedocView.as_view(url_name='schema-v1')),

    path('api/schema-v2/',
         SpectacularJSONAPIView.as_view(api_version="v2"), name='schema-v2'),
    path('api/schema-v2/swagger/',
         SpectacularSwaggerView.as_view(url_name='schema-v2'),
         name='docs-index-v2'),
    path('api/schema-v2/redoc/',
         SpectacularRedocView.as_view(url_name='schema-v2')),
    path('api/v1/', include("modoboa.urls_api_v1", namespace="v1")),
    path('api/v2/', include("modoboa.urls_api_v2", namespace="v2")),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

modoboa/admin/models/base.py
"""Base admin models."""

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils import timezone

from modoboa.core import models as core_models
from modoboa.lib.permissions import (
    grant_access_to_object, ungrant_access_to_object
)


class AdminObjectManager(models.Manager):

    def get_for_admin(self, admin):
        """Return the objects belonging to this admin

        The result is a ``QuerySet`` object, so this function can be used
        to fill ``ModelChoiceField`` objects.
        """
        if admin.is_superuser:
            return self.get_queryset()
        return self.get_queryset().prefetch_related("owners").filter(owners__user=admin)


class AdminObject(models.Model):
    """Abstract model to support dates.

    Inherit from this model to automatically add the "dates" feature
    to another model. It defines the appropriate field and handles
    saves.
    """

    creation = models.DateTimeField(default=timezone.now)
    last_modification = models.DateTimeField(auto_now=True)
    owners = GenericRelation(core_models.ObjectAccess)
    _objectname = None

    objects = AdminObjectManager()

    class Meta:
        abstract = True

    def __init__(self, *args, **kwargs):
        """Custom constructor."""
        super().__init__(*args, **kwargs)
        self._loaded_values = {}

    @classmethod
    def from_db(cls, db, field_names, values):
        """Store loaded values."""
        instance = super().from_db(db, field_names, values)
        instance._loaded_values = dict(zip(field_names, values))
        return instance

    @property
    def objectname(self):
        if self._objectname is None:
            return self.__class__.__name__
        return self._objectname

    def post_create(self, creator):
        grant_access_to_object(creator, self, is_owner=True)

    def save(self, *args, **kwargs):
        creator = kwargs.pop("creator", None)
        super(AdminObject, self).save(*args, **kwargs)
        if creator is not None:
            self.post_create(creator)

    def delete(self):
        ungrant_access_to_object(self)
        super(AdminObject, self).delete()

modoboa/core/views/base.py
"""Base core views."""

from django.contrib.auth import mixins as auth_mixins
from django.urls import reverse
from django.utils.http import is_safe_url
from django.views import generic

from ..extensions import exts_pool


def find_nextlocation(request, user):
    """Find next location for given user after login."""
    if not user.last_login:
        # Redirect to profile on first login
        return reverse("core:user_index")
    nextlocation = request.POST.get("next", request.GET.get("next"))
    condition = (
        nextlocation and
        is_safe_url(nextlocation, request.get_host())
    )
    if condition:
        return nextlocation
    if request.user.role == "SimpleUsers":
        topredir = request.localconfig.parameters.get_value(
            "default_top_redirection")
        if topredir != "user":
            infos = exts_pool.get_extension_infos(topredir)
            nextlocation = infos["topredirection_url"]
        else:
            nextlocation = reverse("core:user_index")
    else:
        nextlocation = reverse("core:dashboard")
    return nextlocation


class RootDispatchView(auth_mixins.LoginRequiredMixin, generic.RedirectView):
    """Handle root dispatching based on role."""

    def get_redirect_url(self):
        """Find proper next hop."""
        return find_nextlocation(self.request, self.request.user)

modoboa/templates/base.html
{% extends "fluid.html" %}

{% load i18n core_tags static %}

{% block pagetitle %}{% trans "MFA" %}{% endblock %}

{% block extra_js %}
    {% block head %}
    {% endblock %}
{% endblock %}


<body id="page-top">
    {% block content %}
    {% endblock %}
</body>

</html>

modoboa/templates/fluid.html
{% extends "nlayout.html" %}
{% block content %}
<div class="container-fluid">
  {% block container_content %}{% endblock %}
</div>
{% endblock %}

modoboa/templates/layout_simple.html
<!DOCTYPE html>
{% load static %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <title>{% block pagetitle %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'css/logo-icon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    <style>
      body {
          padding-top: 60px;
      }
    </style>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>

modoboa/templates/mfa_auth_base.html
<!DOCTYPE html>
{% load i18n core_tags static lib_tags form_tags %}
<html lang="{{ LANGUAGE_CODE }}">
   <!-- Javascript -->
   <script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
   {% if TEMPLATE_DEBUG %}
   <script src="//maxcdn.bootstrapcdn.com/bootlint/0.4.0/bootlint.min.js"></script>
   {% endif %}
   <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% trans "Welcome to Modoboa" %}</title>
    <link rel="icon" type="image/png" href="{% static 'css/logo-icon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/offline.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
    {% block head %}{% endblock %}
  </head>
  <body>
    <div class="container">
      <div id="box" class="col-lg-9 col-lg-offset-1">
        <div id="logo" class="row">
          <ul class="thumbnails">
            <li>
              <div class="col-lg-offset-4 col-lg-5 col-md-offset-4 col-md-5 col-sm-offset-4 col-sm-5">
                <a href="#" class="thumbnail">
                  <img src="{% get_modoboa_logo %}" />
                </a>
              </div>
            </li>
          </ul>
        </div>
        <div class=" divider"></div>
        {% block content %}{% endblock %}
      </div>
      {% for annoucement in annoucements %}
      <div class="col-xs-12 col-sm-offset-3 col-sm-6">{{ annoucement|safe }}</div>
      {% endfor %}
    </div>
  </body>
</html>

modoboa/templates/mfa_email_token_template.html
{% load i18n %}

<html>
<head>
</head>
<body>
Dear {{ username }},<br/>
Your OTP is: <b>{{ otp }}</b>

Thanks
</body>
</html>

modoboa/templates/nlayout.html
<!DOCTYPE html>
{% load static %}
{% load i18n core_tags lib_tags %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block pagetitle %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'css/logo-icon.png' %}" />
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'selectize/dist/css/selectize.bootstrap3.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" />
    {% block extra_css %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">

          <button class="navbar-toggle collapsed pull-right" data-target="#topmenu" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <button class="navbar-toggle collapsed pull-left" data-target="#leftcol" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>


        <div id="topmenu" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if user.is_admin %}
              <li{% if selection == "dashboard" %} class="active"{% endif %}>
                <a name="dashboard" href="{% url 'core:dashboard' %}">
                  <span class="fa fa-home fa-lg"></span>
                </a>
              </li>
            {% endif %}
            {% if selection %}
              {% extensions_menu selection user %}{% core_menu selection user %}
            {% else %}
              {% extensions_menu "" user %}{% core_menu "" user %}
            {% endif %}
            {% load_optionalmenu user %}
            <li class="divider"></li>
            {% if user.is_admin %}
              <li>
                <a name="newadmin" href="/{{ new_admin }}" target="_blank">
                  {% trans "New admin" %}
                </a>
              </li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if selection %}{% user_menu user selection %}{% else %}{% user_menu user "" %}{% endif %}
          </ul>
          {% include "common/top_notifications.html" %}
        </div>
      </div>
    </div>

    {% block content %}{% endblock %}

    <!-- Javascript -->
    <script src="{% static 'jquery/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'moment/min/moment.min.js' %}"></script>
    {% if LANGUAGE_CODE != "en" %}<script src="{{ STATIC_URL }}moment/locale/{{ LANGUAGE_CODE }}.js" type="text/javascript"></script>{% endif %}
    <script src="{% static 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'selectize/dist/js/standalone/selectize.min.js' %}" type="text/javascript"></script>
    {% if TEMPLATE_DEBUG %}
      <script src="//maxcdn.bootstrapcdn.com/bootlint/0.4.0/bootlint.min.js"></script>
    {% endif %}
    <script src="{% static 'js/global.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/csrf.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/confirmation.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/notify.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/poller.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/top_notifications.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    <script type="text/javascript">
      var root_url = "{% url 'core:root' %}".replace(/\/$/, "");
      var top_notifications;
      var userLang = "{{ LANGUAGE_CODE }}";

      set_static_url("{{ STATIC_URL }}");
      $(document).ready(function() {
          top_notifications = new TopNotifications({
              url: "{% url 'core:top_notifications_check' %}",
              interval: {{ notifications_check_interval }}
          });
      });
    </script>
    {% extra_static_content "top" "js" user %}
    {% block extra_js %}{% endblock %}
  </body>
</html>

modoboa/templates/twocols.html
{% extends "fluid.html" %}

{% load core_tags %}

{% block container_content %}
  <div id="leftcol" class="sidebar collapse navbar-collapse">
    {% block leftcol %}{% endblock %}
  </div>
  <div class="main">
    {% block apparea %}{% endblock %}
  </div>
{% endblock %}

{% block extra_js %}
  {% if messages %}{% display_messages messages %}{% endif %}
{% endblock %}