modoboa/core/templates/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'', include('modoboa.urls')),
)

modoboa/core/urls.py
"""Core urls."""

from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = "core"

urlpatterns = [
    path('', views.RootDispatchView.as_view(), name="root"),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),

    path('accounts/login/', views.dologin, name="login"),
    path('accounts/logout/', views.dologout, name="logout"),
    path('accounts/2fa_verify/',
         views.TwoFactorCodeVerifyView.as_view(),
         name='2fa_verify'),

    path('core/', views.viewsettings, name="index"),
    path('core/parameters/', views.parameters, name="parameters"),
    path('core/info/', views.information, name="information"),
    path('core/logs/', views.logs, name="log_list"),
    path('core/logs/page/', views.logs_page, name="logs_page"),
    path('core/top_notifications/check/',
         views.check_top_notifications,
         name="top_notifications_check"),

    path('user/', views.index, name="user_index"),
    path('user/preferences/', views.preferences,
         name="user_preferences"),
    path('user/profile/', views.profile, name="user_profile"),
    path('user/api/', views.api_access, name="user_api_access"),
    path('user/security/', views.security, name="user_security"),
    path('robots.txt', TemplateView.as_view(template_name="core/robots.txt", content_type="text/plain")),
]

modoboa/core/views/dashboard.py
"""Core dashboard views."""

import feedparser
import requests
from dateutil import parser
from requests.exceptions import RequestException

from django.contrib.auth import mixins as auth_mixins
from django.views import generic

from django.conf import settings

from .. import signals

MODOBOA_WEBSITE_URL = "https://modoboa.org/"


class DashboardView(auth_mixins.AccessMixin, generic.TemplateView):
    """Dashboard view."""

    template_name = "core/dashboard.html"

    def dispatch(self, request, *args, **kwargs):
        """Check if user can access dashboard."""
        if not request.user.is_authenticated or not request.user.is_admin:
            return self.handle_no_permission()
        return super(DashboardView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """Add context variables."""
        context = super(DashboardView, self).get_context_data(**kwargs)
        context.update({
            "selection": "dashboard", "widgets": {"left": [], "right": []}
        })
        # Fetch latest news
        if self.request.user.language == "fr":
            lang = "fr"
        else:
            lang = "en"
        context.update({"selection": "dashboard"})

        feed_url = "{}{}/weblog/feeds/".format(MODOBOA_WEBSITE_URL, lang)
        if self.request.user.role != "SuperAdmins":
            custom_feed_url = (
                self.request.localconfig.parameters.get_value("rss_feed_url"))
            if custom_feed_url:
                feed_url = custom_feed_url
        entries = []
        if not settings.DISABLE_DASHBOARD_EXTERNAL_QUERIES:
            posts = feedparser.parse(feed_url)
            for entry in posts["entries"][:5]:
                entry["published"] = parser.parse(entry["published"])
                entries.append(entry)
        context["widgets"]["left"].append("core/_latest_news_widget.html")
        context.update({"news": entries})

        hide_features_widget = self.request.localconfig.parameters.get_value(
            "hide_features_widget")
        if self.request.user.is_superuser or not hide_features_widget:
            url = "{}{}/api/projects/?featured=true".format(
                MODOBOA_WEBSITE_URL, lang)
            features = []
            if not settings.DISABLE_DASHBOARD_EXTERNAL_QUERIES:
                try:
                    response = requests.get(url)
                except RequestException:
                    pass
                else:
                    if response.status_code == 200:
                        features = response.json()
            context["widgets"]["right"].append("core/_current_features.html")
            context.update({"features": features})

        # Extra widgets
        result = signals.extra_admin_dashboard_widgets.send(
            sender=self.__class__, user=self.request.user)
        for _receiver, widgets in result:
            for widget in widgets:
                context["widgets"][widget["column"]].append(
                    widget["template"])
                # FIXME: can raise conflicts...
                context.update(widget["context"])

        return context

modoboa/core/templates/core/_current_features.html
{% load core_tags i18n %}

<!-- Current features to sponsor -->
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">{% trans "Features looking for sponsoring" %}</h3>
  </div>
  <div class="panel-body">
    {% for feature in features %}
      <h4>{{ feature.name }}
        <span class="pull-right">
          <span class="label label-success">{% trans "Goal:" %} {{ feature.goal|currencyfmt }}</span>
        </span>
      </h4>
      <p class="slogan">{{ feature.slogan|safe }}</p>
      <div class="text-center">
        <a href="{{ feature.full_url }}" class="btn btn-primary" target="_blank">
          {% trans "More" %}</a>
      </div>
      {% if not forloop.last %}<hr>{% endif %}
    {% empty %}
      <div class="alert alert-info">{% trans "Nothing to sponsor yet." %}</div>
    {% endfor %}
  </div>
</div>

modoboa/core/templates/core/_latest_news_widget.html
{% load i18n %}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">{% trans "Latest news" %}</h3>
  </div>
  <table class="table">
    <tbody>
      {% for post in news %}
        <tr>
          <td><a href="{{ post.link }}" target="_blank">{{ post.title }}</a></td>
          <td class="text-right">{{ post.published|date:"DATE_FORMAT" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="panel-body text-center">
    {% blocktrans trimmed %}
      Visit the <a href="https://modoboa.org/blog/" target="_blank">official weblog</a> for more information.
    {% endblocktrans %}
  </div>
</div>

modoboa/core/templates/core/api_access.html
{% load i18n form_tags %}

<h2>{% trans "API access" %} <small>{% trans "Control your access to Modoboa API" %}</small></h2>
<hr>
<div class="alert alert-info">
  {% url "docs-index-v2" as api_doc_url %}
  {% blocktrans with url=api_doc_url trimmed %}
    A documentation of the API is available <strong><a href="{{ url }}" target="_blank">here</a></strong>.
  {% endblocktrans %}
</div>
{% if user.auth_token %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">{% trans "API access token" %}</h3>
    </div>
    <div class="panel-body">
      {{ user.auth_token }}
    </div>
  </div>
  <br>
{% endif %}
<form class="form-inline" method="POST" action="{% url 'core:user_api_access' %}"
      id="api_form">
  {% csrf_token %}
  <div class="row">
    <div class="col-sm-2">
      <div class="checkbox">
        <label>
          {{ form.enable_api_access }}
          {{ form.enable_api_access.label }}
        </label>
      </div>
    </div>
    <div class="col-sm-3">
      <button type="submit" class="btn btn-primary" id="update" name="update">{% trans 'Update' %}</button>
    </div>
  </div>
</form>

modoboa/core/templates/core/dashboard.html
{% extends "fluid.html" %}

{% load i18n %}

{% block pagetitle %}{% trans "Dashboard" %}{% endblock %}

{% block container_content %}
  {% if user.is_admin %}
  <div class="alert alert-warning text-center">
    <strong>Want to check the new admin interface?</strong>
    <a class="btn btn-default" style="margin-left: 20px;" href="/{{ new_admin }}" target="_blank">Go to Modoboa v2</a>
  </div>
  {% endif %}

  <div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10">
      <h1>{% blocktrans with user=user.fullname trimmed %}Hello {{ user }}.{% endblocktrans %}</h1>

      <div class="row">
        <div class="col-xs-12 col-sm-6">
          {% for widget in widgets.left %}
            {% include widget %}
          {% endfor %}
        </div>
        <div class="col-xs-12 col-sm-6">
          {% for widget in widgets.right %}
            {% include widget %}
          {% endfor %}
        </div>
      </div>

    </div>
  </div>

{% endblock container_content %}

modoboa/core/templates/core/information.html
{% load i18n core_tags lib_tags %}
<h2>{% trans "Information" %} <small>{% trans "Various information about Modoboa" %}</small></h2><hr>
{% if update_avail %}
<div class="alert alert-block alert-success">
  <h4>{% trans "One or more updates are available!" %}</h4>
  <p>{% trans "Check the following list to find the component(s) that can be updated." %}</p>
</div>
{% endif %}

<h3>{% trans "Applications" %}</h3>
<table id="extensions" class="table table-hover">
  <thead>
    <tr>
      <th>{% trans "Name" %}</th>
      <th>{% trans "Installed version" %}</th>
      <th>{% trans "Last version" %}</th>
      <th>{% trans "Description" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for extension in extensions %}
    <tr{% if extension.update %} class="success"{% endif %}>
      <td>{{ extension.label }}</td>
      <td>{{ extension.version }}</td>
      <td>{% if extension.update %}<strong>{% if extension.changelog_url %}<a href="{{ extension.changelog_url }}">{{ extension.last_version }}</a>{% else %}{{ extension.last_version }}{% endif %}</strong>{% else %}{{ extension.last_version }}{% endif %}</td>
      <td>{{ extension.description }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<h3>{% trans "Active users" %}</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>{% trans "Name" %}</th>
      <th>{% trans "Role" %}</th>
      <th>{% trans "Last login" %}</th>
    </tr>
  </thead>
  <tbody>
    {% connected_users as users %}{% for u in users %}
    <tr>
      <td>{{ u.username }}</td>
      <td>{{ u.role }}</td>
      <td>{{ u.last_login }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

modoboa/core/templates/core/logs.html
{% load i18n %}
<h2>{% trans "Logs" %} <small>{% trans "Previously on Modoboa..." %}</small></h2><hr>
<table id="logs_table" class="table">
  <thead>
    <tr>
      <th class="sortable" data-sort_order="date_created" width="20%">{% trans "Date" %}</th>
      <th class="sortable" data-sort_order="level" width="7%">{% trans "Level" %}</th>
      <th class="sortable" data-sort_order="logger" width="15%">{% trans "Logger" %}</th>
      <th class="sortable" data-sort_order="message" width="">{% trans "Message" %}</th>
    </tr>
  </thead>
  <tbody>
    {% include "core/logs_page.html" %}
  </tbody>
</table>

modoboa/core/templates/core/logs_page.html
{% load core_tags %}

{% for l in logs %}
<tr>
  <td>{{ l.date_created|date:"SHORT_DATETIME_FORMAT" }}</td>
  <td>{{ l.level|colorize_level|safe }}</td>
  <td>{{ l.logger }}</td>
  <td>{{ l.message }}</td>
</tr>
{% endfor %}

modoboa/core/templates/core/parameters.html
{% load i18n lib_tags %}
<h2>{% trans "Parameters" %} <small>{% trans "Configure Modoboa" %}</small></h2><hr />
<form id="parameters_form" method="POST" action="{% url 'core:parameters' %}" class="form-horizontal" novalidate>{% csrf_token %}
  {% include "parameters/base_form.html" %}
  <hr>
  <button type="submit" class="btn btn-primary col-xs-offset-4 col-xs-4" name="update">{% trans 'Save' %}</button>
</form>

modoboa/core/templates/core/settings_header.html
{% extends "twocols.html" %}
{% load i18n lib_tags core_tags %}
{% load static %}

{% block pagetitle %}{% trans "Modoboa settings" %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.sortable.css' %}" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.infinitescroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/history.js' %}"></script>
<script type="text/javascript" src="{% static 'js/listing.js' %}"></script>
<script type="text/javascript" src="{% static 'js/twocols_nav.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.sortable.js' %}"></script>
<script type="text/javascript" src="{% static 'core/js/settings.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    var settings = new Settings({
        deflocation: "parameters/",
        formid: "settings_form",
        divid: "settings_content",
        reload_exceptions: ["extensions"],
        load_page_url: "{% url 'core:logs_page' %}"
    });
});
</script>
{% endblock %}

{% block leftcol %}{% admin_menu left_selection user %}{% endblock %}

{% block apparea %}<div id="settings_content"></div>{% endblock %}

modoboa/core/templates/core/user_index.html
{% extends "twocols.html" %}{% load i18n core_tags lib_tags %}
{% load static %}

{% block pagetitle %}{% trans "Settings" %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/userprefs.css' %}" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/history.js' %}"></script>
<script type="text/javascript" src="{% static 'js/listing.js' %}"></script>
<script type="text/javascript" src="{% static 'js/twocols_nav.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript">
 {% extra_static_content "user_index" "js" user %}

 function preferencesCallback() {
     $(document).trigger('preferencesLoaded');
 }

 $(document).ready(function() {
     var userprefs = new TwocolsNav({
         deflocation: "profile/",
         formid: "uprefs_form",
         divid: "uprefs_content",
         reload_exceptions: ["profile", "api"]
     });
 });
</script>
{% endblock %}

{% block leftcol %}{% uprefs_menu left_selection user %}{% endblock %}

{% block apparea %}<div id="uprefs_content"></div>{% endblock %}

modoboa/core/templates/core/user_preferences.html
{% load i18n %}
<h2>{% trans "Preferences" %} <small>{% trans "Customize Modoboa" %}</small></h2>
<hr>
{% if forms %}
  <form class="form-horizontal" method="POST" action="{% url 'core:user_preferences' %}" 
        id="parameters_form">
    {% csrf_token %}
    {% include "parameters/base_form.html" %}
    <hr>
    <button type="submit" class="btn btn-primary col-xs-offset-4 col-xs-4" name="update">{% trans 'Save' %}</button>
  </form>
{% else %}
  <div class="alert alert-info">
    {% trans "No preferences available." %}
  </div>
{% endif %}

modoboa/core/templates/core/user_profile.html
{% load i18n form_tags %}

<h2>{% trans "Profile" %} <small>{% trans "Update your personal information" %}</small></h2>
<hr>
<form class="form-horizontal" method="POST" action="{% url 'core:user_profile' %}"
      id="uprefs_form">
  {% csrf_token %}
  {% render_form form %}
  {% if show_password_url %}
    <div class="row">
      <div class="col-sm-offset-4 col-sm-8">
        <a href="{{ password_url }}" target="_blank">
          {% trans "Click here to update your password" %}
        </a>
      </div>
    </div>
  {% endif %}
  <div class="form-actions" style="margin-top: 15px;">
    <button type="submit" class="btn btn-primary btn-lg col-sm-offset-4 col-sm-4" id="update" name="update">{% trans 'Update' %}</button>
  </div>
</form>

modoboa/core/templates/core/user_security.html
{% load i18n static %}
<h2>{% trans "Security" %}</h2>
<hr>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{% trans "Two-Factor authentication" %}</h3>
  </div>

  <div class="panel-body">
    {% if qrcode %}
      <div class="row">
        <div class="col-sm-4">
          {{ qrcode|safe }}
        </div>
        <div class="col-sm-6">
          <div class="alert alert-info">
            {% blocktrans trimmed %}
              Install a soft token authenticator like FreeOTP or Google
              Authenticator from your application repository and use that
              app to scan this QR code.
            {% endblocktrans %}
          </div>
          <form>
            <div class="form-group">
              <label class="control-label">{% trans "Pin code" %}</label>
              <input id="pin-code" class="form-control">
            </div>
            <button id="finalize-tfa-setup" class="btn btn-primary col-sm-12">{% trans "Register" %}</button>
          </form>
        </div>
    {% elif tokens %}
        <div class="alert alert-success">
          {% blocktrans trimmed %}
            Congratulations! Two-Factor Authentication is now enabled for your account.
          {% endblocktrans %}
        </div>
        <p>
          {% blocktrans trimmed %}
            The following recovery codes can be used one time each to
            let you regain access to your account, in case you lose your
            phone for example. Make sure to save them in a safe place,
            otherwise you won't be able to access your account anymore.
          {% endblocktrans %}
        </p>
        <br>
        <ul>
          {% for token in tokens %}
            <li>{{ token }}</li>
          {% endfor %}
        </ul>
    {% elif user.tfa_enabled %}
        <div class="alert alert-info">
          {% blocktrans trimmed %}
            Two-Factor Authentication is enabled for your account.
          {% endblocktrans %}
        </div>
        <a id="deactivate-tfa" class="btn btn-danger" href="{% url 'api:account-tfa-disable' %}">
          {% trans "Disable 2FA" %}
        </a>
        <a id="tfa-refresh-codes" class="btn btn-default" href="{% url 'api:account-tfa-reset-codes' %}">
          {% trans "Reset recovery codes" %}
        </a>
    {% else %}
        <div class="alert alert-info text-center">
          {% blocktrans trimmed %}
            Two-Factor Authentication (2FA) is not yet activated for
            your account. Enabling this feature will increase your
            account's security.
          {% endblocktrans %}
        </div>
        <div class="text-center">
          <button id="start-tfa-setup" class="btn btn-success">
            {% trans "Enable 2FA" %}
          </button>
        </div>
    {% endif %}
      </div>
  </div>
  <div id="codes-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">{% trans "Close" %}</span></button>
          <h3 class="modal-title">{% trans "New recovery codes" %}</h3>
        </div>
        <div class="modal-body">
          <div class="alert alert-info" style="overflow-wrap: break-word;">
            <strong>{% trans "Here are your new recovery codes. " %}</strong><br>
            {% blocktrans trimmed %}
              The following recovery codes can be used one time each to
              let you regain access to your account, in case you lose your
              phone for example. Make sure to save them in a safe place,
              otherwise you won't be able to access your account anymore.
            {% endblocktrans %}
          </div>
          <div id="tfa-codes-area"></div>
        </div>
        <div class="modal-footer">
          <a class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</a>
        </div>
      </div>
    </div>
  </div>